import express from 'express';
import helmet from 'helmet';
import multer from 'multer';
import fetch from 'node-fetch';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { scanFromGithub } from './scripts/github-scanner.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const app = express();
// SECURITY: Aikido High #12 flagged missing security response headers. Helmet
// sets X-Content-Type-Options, X-Frame-Options, Strict-Transport-Security,
// Cross-Origin-Resource-Policy, Referrer-Policy, and others with sensible
// defaults. CSP is disabled here because the bundled Vite React app uses
// inline styles from styled components; if we later tighten CSP, keep the
// rest of Helmet on.
app.use(helmet({ contentSecurityPolicy: false }));
// Airtable's uploadAttachment endpoint accepts up to 5 MB per file when base64-encoded.
// Cap multer at 5 MB so we fail fast instead of building a payload Airtable will reject.
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024 } });

const AIRTABLE_TOKEN = process.env.AIRTABLE_TOKEN;
const BASE_ID = 'appK5TjjSK9rmqx2Y';
const TABLE_ID = 'tbl5bwkO1aAWVUfc0';
const SCREENSHOT_FIELD_ID = 'fld2rWRcARrx3loN5'; // "Screenshot" multipleAttachments
const AT_URL = `https://api.airtable.com/v0/${BASE_ID}/${TABLE_ID}`;

const SLACK_BOT_TOKEN = process.env.SLACK_BOT_TOKEN;
const SLACK_NOTIFY_CHANNEL = process.env.SLACK_NOTIFY_CHANNEL;

app.use(express.json());
app.use(express.static(path.join(__dirname, 'dist')));

app.get('/health', (_req, res) => res.status(200).send('OK'));

async function airtableGet(params = '') {
  const r = await fetch(`${AT_URL}${params}`, {
    headers: { Authorization: `Bearer ${AIRTABLE_TOKEN}` }
  });
  if (!r.ok) throw new Error(`Airtable GET failed: ${r.status} ${await r.text()}`);
  return r.json();
}

async function fetchAllRecords() {
  let records = [];
  let offset;
  do {
    const qs = new URLSearchParams();
    qs.append('sort[0][field]', 'Submitted At');
    qs.append('sort[0][direction]', 'desc');
    qs.append('pageSize', '100');
    if (offset) qs.append('offset', offset);
    const data = await airtableGet(`?${qs.toString()}`);
    records = records.concat(data.records || []);
    offset = data.offset;
  } while (offset);
  return records;
}

app.get('/api/bugs', async (_req, res) => {
  try {
    const records = await fetchAllRecords();
    res.json({ records });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

// ------- Component manifest + status overlay -------
// The manifest is generated by scripts/scan-cast-components.mjs and committed
// to the repo as component-manifest.json. It is the DEFAULT data source for
// GET /api/components — fast, no GitHub API burn on every page visit.
//
// Users can force a live re-scan against CAST-Lighting/cast-website master via
// POST /api/components/refresh. That endpoint fetches CAST source through the
// GitHub API (PAT in env), runs the same scan logic as the CLI script (shared
// module in scripts/scan-lib.mjs), and caches the result in memory for the
// life of the process. Subsequent GET /api/components calls prefer the cache
// over the committed manifest, so a refresh sticks until the service restarts
// or someone forces another refresh.
//
// A per-process cooldown protects the GitHub API from accidental hammering —
// the UI also disables the button for 30s after each click.
const MANIFEST_PATH = path.join(__dirname, 'component-manifest.json');
const REFRESH_COOLDOWN_MS = 30 * 1000;

// In-memory cache: last successful live scan. Not persisted — a service
// restart falls back to the committed manifest, which is the correct
// baseline behaviour (fresh deploy = fresh manifest bake).
let refreshCache = null;         // parsed manifest object
let lastRefreshAt = 0;           // epoch ms of last successful refresh

// Human-readable Airtable Component field values → CAST code component names.
// The Airtable field is a curated singleSelect, so this mapping is intentional.
//
// Bugs whose Component field is "Other" (with free-text in Component (Other))
// are left UNMAPPED on purpose — see CAST-014 "Other: 404 error" for the
// canonical example. We cannot reliably infer the code component from a
// free-text string, and guessing wrong would flip the wrong component to
// status "Bug" on the Components tab. If a specific "Other" bug needs to
// flag a real component (e.g. NotFoundHero for CAST-014), edit the Airtable
// record: set Component to the curated singleSelect value ("Not Found Hero")
// and clear the "Other" text. Then the overlay picks it up automatically.
const AIRTABLE_COMPONENT_TO_CODE_NAME = {
  'Site Navbar': 'SiteNavbar',
  'Site Footer': 'SiteFooter',
  'Navigation Topper': 'NavigationTopper',
  'Hero Banner': 'HeroBanner',
  'Category Grid': 'CategoryGrid',
  'Shop Grid': 'ShopGrid',
  'Product Gallery': 'ProductGallery',
  'Bundle Products': 'BundleProducts',
  'Parts Grid': 'PartsGrid',
  'Product Hero': 'ProductHero',
  'Product Description': 'ProductDescription',
  'Product Documents': 'ProductDocuments',
  'Product FAQ': 'ProductFAQ',
  'About Content': 'AboutContent',
  'Blog Grid': 'BlogGrid',
  'Blog Post Content': 'BlogPostContent',
  'Content Media': 'ContentMedia',
  'Media Gallery': 'MediaGallery',
  'Brand Logos': 'BrandLogos',
  'Comparison Section': 'ComparisonSection',
  'Reviews Carousel': 'ReviewsCarousel',
  'Trade Pro Section': 'TradeProSection',
  'Ready CTA': 'ReadyCTA',
  'Newsletter CTA (Full)': 'NewsletterCtaFull',
  'Newsletter Form (Small)': 'NewsletterFormSmall',
  'Contact Section': 'ContactSection',
  'General Contact Form': 'GeneralContactForm',
  'Trade Pro Signup': 'TradeProSignup',
  'Retail Signup': 'RetailSignup',
  'Contractor Finder': 'ContractorFinder',
  'Distributor Finder': 'DistributorFinder',
  'Search Results': 'SearchResults',
  'Not Found Hero': 'NotFoundHero',
  'Login Section': 'LoginSection',
  'Favorites Grid': 'FavoritesGrid',
  'Quotes List': 'QuotesList',
  'Quote Detail': 'QuoteDetail',
  'Orders Grid': 'OrdersGrid',
  'Order Detail': 'OrderDetail',
  'Certifications & Patents': 'PatentsList',
  'Rich Text Section': 'RichTextSection',
  'GDPR Popup': 'GDPRPopup',
  'Events Grid': 'EventsGrid',
  'Documents & Downloads': 'DocumentsDownloads',
};

function loadManifestFromDisk() {
  try {
    const raw = fs.readFileSync(MANIFEST_PATH, 'utf8');
    return JSON.parse(raw);
  } catch (e) {
    console.error('[components] failed to load manifest:', e.message);
    return { generatedAt: null, counts: {}, components: [] };
  }
}

// Prefer the in-memory refresh cache if present — that means someone hit the
// Refresh Components button since the process started and we should keep
// serving that fresher view until they hit it again or the service restarts.
//
// IMPORTANT: return a deep copy. The GET handler mutates `c.status` and
// `c.openBugs` on the returned components (overlay logic). If we handed
// back the cache object by reference, those mutations would poison the
// cache — a component flipped to "Bug" during one GET would stay "Bug"
// on the next even after the Airtable record is Resolved. Cache stores
// the RAW scan result; overlay happens per-request against fresh bugs.
function loadManifest() {
  const src = refreshCache || loadManifestFromDisk();
  return {
    ...src,
    components: (src.components || []).map((c) => ({ ...c, openBugs: undefined })),
  };
}

app.get('/api/components', async (_req, res) => {
  try {
    const manifest = loadManifest();
    const components = Array.isArray(manifest.components) ? [...manifest.components] : [];

    // Collect open bugs by mapped code component name
    let openBugsByComponent = new Map();
    try {
      const records = await fetchAllRecords();
      for (const r of records) {
        const f = r.fields || {};
        if (f.Type === 'Feature') continue;
        if (f.Status === 'Resolved') continue;
        const airtableComp = f.Component;
        if (!airtableComp || airtableComp === 'Other') continue;
        const codeName = AIRTABLE_COMPONENT_TO_CODE_NAME[airtableComp];
        if (!codeName) continue;
        if (!openBugsByComponent.has(codeName)) openBugsByComponent.set(codeName, []);
        openBugsByComponent.get(codeName).push({
          bugId: f['Bug ID'],
          status: f.Status,
          description: f.Description,
        });
      }
    } catch (e) {
      console.error('[components] failed to fetch bugs, returning manifest only:', e.message);
    }

    // Overlay bugs onto manifest
    for (const c of components) {
      const bugs = openBugsByComponent.get(c.componentName);
      if (bugs && bugs.length) {
        c.status = 'Bug';
        c.openBugs = bugs;
      } else if (!c.openBugs) {
        c.openBugs = [];
      }
    }

    // Recount
    const counts = components.reduce(
      (acc, r) => ((acc[r.status] = (acc[r.status] || 0) + 1), acc),
      {}
    );

    res.json({
      generatedAt: manifest.generatedAt,
      castRepo: manifest.castRepo,
      totalRegistrations: components.length,
      counts,
      components,
    });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

/**
 * Force a live re-scan of CAST-Lighting/cast-website master via the GitHub API.
 * Response mirrors GET /api/components so the frontend can drop it straight in.
 * Server-side cooldown mirrors the 30-second UI cooldown, so accidental parallel
 * clicks (multiple tabs, quick reloads) also can't hammer GitHub.
 */
app.post('/api/components/refresh', async (_req, res) => {
  const now = Date.now();
  const sinceLast = now - lastRefreshAt;
  if (lastRefreshAt && sinceLast < REFRESH_COOLDOWN_MS) {
    const retryAfter = Math.ceil((REFRESH_COOLDOWN_MS - sinceLast) / 1000);
    res.set('Retry-After', String(retryAfter));
    return res.status(429).json({
      error: `Refresh on cooldown — try again in ${retryAfter}s`,
      retryAfter,
    });
  }

  try {
    const freshManifest = await scanFromGithub();
    refreshCache = freshManifest;
    lastRefreshAt = Date.now();

    // Overlay Airtable bugs onto the fresh manifest exactly like GET does,
    // so the UI sees "Bug" statuses without a second round-trip.
    // Deep copy so the overlay's mutations don't poison the cache — see the
    // note on loadManifest() above for why.
    const components = freshManifest.components.map((c) => ({ ...c, openBugs: undefined }));
    let openBugsByComponent = new Map();
    try {
      const records = await fetchAllRecords();
      for (const r of records) {
        const f = r.fields || {};
        if (f.Type === 'Feature') continue;
        if (f.Status === 'Resolved') continue;
        const airtableComp = f.Component;
        if (!airtableComp || airtableComp === 'Other') continue;
        const codeName = AIRTABLE_COMPONENT_TO_CODE_NAME[airtableComp];
        if (!codeName) continue;
        if (!openBugsByComponent.has(codeName)) openBugsByComponent.set(codeName, []);
        openBugsByComponent.get(codeName).push({
          bugId: f['Bug ID'],
          status: f.Status,
          description: f.Description,
        });
      }
    } catch (e) {
      console.error('[refresh] bug overlay failed, returning manifest only:', e.message);
    }

    for (const c of components) {
      const bugs = openBugsByComponent.get(c.componentName);
      if (bugs && bugs.length) {
        c.status = 'Bug';
        c.openBugs = bugs;
      } else if (!c.openBugs) {
        c.openBugs = [];
      }
    }

    const counts = components.reduce(
      (acc, r) => ((acc[r.status] = (acc[r.status] || 0) + 1), acc),
      {}
    );

    res.json({
      refreshed: true,
      generatedAt: freshManifest.generatedAt,
      castRepo: freshManifest.castRepo,
      totalRegistrations: components.length,
      counts,
      components,
    });
  } catch (e) {
    console.error('[refresh] scan failed:', e.message);
    res.status(502).json({ error: `Refresh failed: ${e.message}` });
  }
});

async function nextBugId() {
  const records = await fetchAllRecords();
  let max = 0;
  for (const r of records) {
    const id = r.fields?.['Bug ID'];
    if (typeof id === 'string') {
      const m = id.match(/CAST-(\d+)/);
      if (m) max = Math.max(max, parseInt(m[1], 10));
    }
  }
  return `CAST-${String(max + 1).padStart(3, '0')}`;
}

/**
 * Upload an attachment to an existing Airtable record via the content API.
 * Airtable removed support for `data:` URLs in attachment fields, so we have to
 * use the uploadAttachment endpoint (introduced 2024). Up to 5 MB per file.
 * Returns the attachment URL on success, or null on failure (never throws — the
 * record is already created, so a screenshot failure must not break the response).
 */
async function uploadScreenshot(recordId, file) {
  try {
    const contentType = file.mimetype || 'image/png';
    const filename = file.originalname || 'screenshot.png';
    const base64 = file.buffer.toString('base64');
    const url = `https://content.airtable.com/v0/${BASE_ID}/${recordId}/${SCREENSHOT_FIELD_ID}/uploadAttachment`;
    const r = await fetch(url, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${AIRTABLE_TOKEN}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ contentType, file: base64, filename })
    });
    if (!r.ok) {
      const txt = await r.text().catch(() => '');
      console.error(`[screenshot] upload failed for ${recordId}: ${r.status} ${txt}`);
      return null;
    }
    const data = await r.json().catch(() => null);
    // Response shape: { id, createdTime, fields: { Screenshot: [{ id, url, ... }] } }
    const attachments = data?.fields?.[SCREENSHOT_FIELD_ID] || data?.fields?.Screenshot;
    if (Array.isArray(attachments) && attachments[0]?.url) return attachments[0].url;
    return null;
  } catch (err) {
    console.error('[screenshot] upload exception:', err.message);
    return null;
  }
}

/**
 * Post a notification to Slack. Wrapped in try/catch so a Slack failure
 * never blocks the user-facing submission. Uses <!channel> per the
 * Railway silent-notification gotcha.
 */
async function notifySlack({ bugId, submittedBy, requestType, page, pageOther, component, componentOther, description, screenshotUrl }) {
  if (!SLACK_BOT_TOKEN || !SLACK_NOTIFY_CHANNEL) return;
  try {
    const isFeature = requestType === 'Feature';
    const emoji = isFeature ? ':sparkles:' : ':bug:';
    const label = isFeature ? 'Feature request' : 'New CAST bug';
    let text;
    if (isFeature) {
      text = `<!channel> ${emoji} ${label} ${bugId} from ${submittedBy}\n*Description:* ${description}`;
    } else {
      const pageText = page + (pageOther ? ` (${pageOther})` : '');
      const componentText = component + (componentOther ? ` (${componentOther})` : '');
      const screenshotLine = screenshotUrl ? `\n*Screenshot:* ${screenshotUrl}` : '';
      text = `<!channel> ${emoji} ${label} ${bugId} from ${submittedBy}\n*Page:* ${pageText}\n*Component:* ${componentText}\n*Description:* ${description}${screenshotLine}`;
    }
    const r = await fetch('https://slack.com/api/chat.postMessage', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${SLACK_BOT_TOKEN}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ channel: SLACK_NOTIFY_CHANNEL, text })
    });
    if (!r.ok) {
      console.error('[slack] HTTP error:', r.status, await r.text().catch(() => ''));
      return;
    }
    const json = await r.json().catch(() => null);
    if (!json?.ok) console.error('[slack] API error:', json?.error || 'unknown');
  } catch (err) {
    console.error('[slack] exception:', err.message);
  }
}

app.post('/api/bugs', upload.single('screenshot'), async (req, res) => {
  try {
    const { submittedBy, page, pageOther, component, componentOther, description, requestType } = req.body;

    // Normalize request type — default to Bug for backward compat
    const normalizedType = requestType === 'Feature' ? 'Feature' : 'Bug';
    const isFeature = normalizedType === 'Feature';

    // For bugs: page, component, and description all required
    // For features: only submittedBy and description are required
    if (!submittedBy || !description) {
      return res.status(400).json({ error: 'Missing required fields' });
    }
    if (!isFeature && (!page || !component)) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    const bugId = await nextBugId();
    const fields = {
      'Bug ID': bugId,
      'Submitted By': submittedBy,
      'Description': description,
      'Status': 'New',
      'Type': normalizedType,
      'Submitted At': new Date().toISOString()
    };

    if (!isFeature) {
      fields['Page'] = page;
      fields['Component'] = component;
      if (page === 'Other' && pageOther) fields['Page (Other)'] = pageOther;
      if (component === 'Other' && componentOther) fields['Component (Other)'] = componentOther;
    }

    // Step 1: create the record (without the screenshot — that requires a record ID first)
    const createRes = await fetch(AT_URL, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${AIRTABLE_TOKEN}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ fields })
    });
    if (!createRes.ok) {
      const txt = await createRes.text();
      return res.status(500).json({ error: `Airtable create failed: ${txt}` });
    }
    const created = await createRes.json();
    const recordId = created.id;

    // Step 2: if a screenshot was uploaded, attach it via Airtable's content API.
    // Never block the response on this — log + continue if it fails.
    let screenshotUrl = null;
    let screenshotFailed = false;
    if (req.file) {
      screenshotUrl = await uploadScreenshot(recordId, req.file);
      if (!screenshotUrl) screenshotFailed = true;
    }

    // Step 3: Slack notification (fire-and-forget, never blocks).
    notifySlack({ bugId, submittedBy, requestType: normalizedType, page, pageOther, component, componentOther, description, screenshotUrl })
      .catch((err) => console.error('[slack] outer exception:', err.message));

    res.json({ success: true, bugId, screenshotFailed, requestType: normalizedType });
  } catch (e) {
    // Multer file-size errors land here
    if (e?.code === 'LIMIT_FILE_SIZE') {
      return res.status(413).json({ error: 'Screenshot too large — maximum 5 MB.' });
    }
    res.status(500).json({ error: e.message });
  }
});

app.get('*', (_req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`cast-bug-reporter listening on ${PORT}`));
